name: CI-CD-Text-Stats

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build
      - name: Build
        run: |
          pip install -r deps.txt
          echo "Build done ✅"

      # Step 3: Test
      - name: Test
        run: |
          pytest
          echo "Tests done ✅"

      # Step 4: Deploy
      - name: Deploy
        if: success()   # runs only if previous steps passed
        run: |
          echo "Deployed at $(date)" >> deployment.log
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add deployment.log
          git commit -m "Auto-deploy update" || echo "No changes to commit"
          echo "Deploy done ✅"

