name: CI-CD Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build
      - name: Build
        run: |
          echo "Simulating build..."
          echo "Build done ✅"

      # Step 3: Test
      - name: Test
        run: |
          echo "Simulating tests..."
          echo "Tests done ✅"

      # Step 4: Deploy
      - name: Deploy
        if: success()
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Set remote to use your PAT
          git remote set-url origin https://$PAT_TOKEN@github.com/Vamseedhar159/text-stats-github-actions.git
          
          # Update deployment log
          echo "Deployment successful at $(date)" >> deployment.log
          git add deployment.log
          git commit -m "Auto-deploy update" || echo "No changes to commit"
          git push origin HEAD:main
          echo "Deploy done ✅"

